[package]
name = "logic"
version = "0.1.0"
authors = ["Pedro Fanha <ixjf@outlook.com>"]
edition = "2018"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
id_tree = { git = "https://github.com/ixjf/id-tree", features = ["serde_support"] } # "1.3.0"
serde = { version = "1.0", optional = true, features = ["derive"] }
snowflake = { version = "1.3.0", features = ["serde_support"] }

[features]
serde_support = ["serde"]